### ISSUE TITLE
When --no-contrast and --no-whitebalance are not used, sometimes there are artifacts

### ISSUE THREAD

**Issue by raduprv** [PetteriAimonen/focus-stack#1]
Look at the upper part of the focus stacked picture, at the edge of the top middle left raspberry (last picture is the focus stacked one).

![IMG_8342](https://user-images.githubusercontent.com/1095519/76160264-4ceb4400-6131-11ea-8b29-5fd3a3c6c6d6.JPG)
![IMG_8343](https://user-images.githubusercontent.com/1095519/76160266-4e1c7100-6131-11ea-8b9e-3a28d623378a.JPG)
![IMG_8344](https://user-images.githubusercontent.com/1095519/76160267-4eb50780-6131-11ea-86df-d084a393207d.JPG)
![IMG_8345](https://user-images.githubusercontent.com/1095519/76160268-4f4d9e00-6131-11ea-8f1d-206864821b3e.JPG)
![IMG_8346](https://user-images.githubusercontent.com/1095519/76160269-4fe63480-6131-11ea-8f46-66e47e80dae5.JPG)
![IMG_8347](https://user-images.githubusercontent.com/1095519/76160270-507ecb00-6131-11ea-9b35-45b6cc418d81.JPG)
![IMG_8341](https://user-images.githubusercontent.com/1095519/76160271-507ecb00-6131-11ea-8cf0-9b500fb86a3f.JPG)
![img_000001](https://user-images.githubusercontent.com/1095519/76160274-5a083300-6131-11ea-9736-65897363d326.jpg)

**Comment by PetteriAimonen** [comment]
Hmm yeah, looks like some overflow or saturation in the contrast matching logic.

**Comment by raduprv** [comment]
Great, thanks for the quick fix! Can you please update the windows binaries when you have some time?
