### ISSUE TITLE
[BUG] Deadlock in Worker

### ISSUE THREAD

**Issue by stiffsen** [PetteriAimonen/focus-stack#15]
Hi! On one of the computers I ran this on, the software would reproducibly hang eventually (I am on Windows). Using a debugger, I found that this is due to a deadlock in Worker when trying to set the mutex via unique_lock.

My hunch was that this deadlock is due to recursively locking the mutex in the same thread. Hence, I simply replaced std::mutex with std::recursive_mutex and std::condition_variable with std::condition_variable_any, which fixed the issue for me.

**Comment by PetteriAimonen** [comment]
Do you have a more specific call stack of where the problem occurs?

**Comment by stiffsen** [comment]
The deadlock happend when executing the verbose logging in Worker. When I disabled verbose-logging, it happened at another location, 'though. I think it was somewhere directly after returning from task().

**Comment by PetteriAimonen** [comment]
Hmm, ok. I'll keep an eye out for it.

I don't think recursive mutexes are necessarily the correct solution here, though they may make the problem disappear.

**Comment by pjrose** [comment]
Rain into the same issue on windows 10, I did not see the issue with the test images provided, only when I started stacking much larger ones - qty 20 25MP images in my case - sitffsen's recursive_mutex and condition_variable_any change worked for me, too.

**Comment by PetteriAimonen** [comment]
@pjrose Could you provide the following for debugging:

1) Last lines of debug output when run with `--verbose` and hangs up.

2) Crash dump when the program is hung up. You can save a crash dump from task manager by right-clicking on the program:

![Task manager crash dump](https://www.barco.com/images/knowledgebase/repository/b11bd164-a1c6-4907-8747-4231ce339cd8.png)

**Comment by PetteriAimonen** [comment]
@pjrose As far as I know, the Windows dumps only include data from the single process, so just the images that were being processed. You can mail me at petteri.aimonen (at) devembedded.com

Regarding the recursive_mutex fix, it sounds like it works, but I would like to get to the root of the problem and fix it there if possible. Through reading the code I cannot spot any place where `Worker` would call elsewhere while having `m_mutex` locked.

**Comment by pjrose** [comment]
Ran the new build 12 times in a row, all ran without issue, no more deadlock. nice!
