### ISSUE TITLE
Can this work on IOS (Iphone/iPad)

### ISSUE THREAD

**Issue by nsmith1024** [PetteriAimonen/focus-stack#17]
Can this work on IPad or iPhone?

**Comment by PetteriAimonen** [comment]
If you compile it for it, yes.

But considering the costs involved in doing development for iOS, I'm not planning to add support myself.

**Comment by nsmith1024** [comment]
What cost do you mean?

**Comment by PetteriAimonen** [comment]
Yes, cost of my time is probably the largest. But I don't even own any Apple hardware, so that would add up also.

In short, I'm not interested in doing that.

**Comment by nsmith1024** [comment]
Apple people and IOS users are the ones doing the most photography.
