### ISSUE TITLE
Silent option

### ISSUE THREAD

**Issue by MichaelTimmermans** [PetteriAimonen/focus-stack#31]
Hello, i would love to see a silent option to be added to the tool. If i run this on a large set of images with multiple stacks from multiple anles (like photogrammetry) i get loads of popup screens that sort of get in the way of using my computer. It would be nice if the tool could run without showing the popup, or at least without focussing it.

**Comment by PetteriAimonen** [comment]
Hmm, I assume this is on Windows?

Because the program itself is a command line application. I guess Windows will open a command prompt by default, not sure if there is some option to affect it.

**Comment by MichaelTimmermans** [comment]
Hi, 

yes i found a way to overrule it in the batch script i made. issue can be ignored! Thanks for the fast reply, did'nt even have time to reply with my sollution hehe.
