### ISSUE TITLE
Help with Installing on RPI CM4 Bullseye

### ISSUE THREAD

**Issue by ringmybell** [PetteriAimonen/focus-stack#45]
Hello, I am a beginner software programmer, and reached my current limits of understanding. 

I am trying to install focus-stack on a Raspberry Pi CM4 module with latest version of Bullseye. 

I download from git, setup a folder, extract the .tz.gx file. When I try to run the make file I get
```
"mkdir: cannot creat a directory 'build': Permission deinied
Package opencv was not found in the pkg-config search path
Perhaps you should add the directory containing opencv.pc to the PKG_CONFIG_PATH environment variable
```

On the Opencv site it states that opencv.pc is not supported  "Due to complexity of configuration process resulting .pc file can contain incomplete list of third-party dependencies and may not work in some configurations, especially for static builds. This feature is not officially supported since 4.x version and is disabled by default."
https://docs.opencv.org/4.x/db/d05/tutorial_config_reference.html

Is there a way to modify the make file downloaded from here and hard code the directories to opencv files instead of using pkg-config ?? Or any other ideas? 

Thanks 

PS I also tried Debian package method https://github.com/PetteriAimonen/focus-stack
```
sudo apt install debhelper devscripts
make builddeb
sudo dpkg -i DEBUILD/focus-stack*.deb
```

It wont get past the make builddeb stage, this is the error
`make: *** No rule to make target 'builddeb'. Stop.`

I feel like there is a missing step(s) above and this is just a high level summary, but I dont understand what I am missing. So I tried to install from git.....

**Comment by PetteriAimonen** [comment]
> mkdir: cannot creat a directory 'build': Permission deinied

Sounds like you may have some basic issue with the file permissions. Maybe you have unnecessarily used sudo while extracting?

If you don't have pkg-config files for OpenCV, you can edit the Makefile or add overrides in Makefile.local.

**Comment by ringmybell** [comment]
Thanks, this is solved. 

I did a fresh build and install of OpenCV using the compile method so the PKG_CONFIG_PATH was included.

Everything is working now.
