### ISSUE TITLE
Build process on MacOS

### ISSUE THREAD

**Issue by alsmithson** [PetteriAimonen/focus-stack#5]
Could you provide guidance in the readme on how to build this on MacOS? I am not a computer geek, but I would like to use this program in my photography.

**Comment by PetteriAimonen** [comment]
Yeah, I could. But it may be a while before I have time to test it out.

Here is a guess, but I haven't tested this yet:

1. [Install homebrew](https://brew.sh/): `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"`

2. Install OpenCV and git: `brew install git opencv`

3. Clone the focus-stack repository: `git clone https://github.com/PetteriAimonen/focus-stack.git` and go there: `cd focus-stack`

4. Build: `make` and `make install`

**Comment by alsmithson** [comment]
Thanks. It took 6 hours to get OpenCV built (thanks to its seemingly thousands of highly specific dependencies). Your make went well, but make install did not like the -D switch. Deleted the -D and the install seemed to work. I can launch you executable fine, but I'm too exhausted to actually try making a focus stack right now.

**Comment by PetteriAimonen** [comment]
Thanks for trying it out! I'll keep this open until I've added the build instructions to docs.

I guess I should provide binary package for Mac OS X also, to avoid the long build.

**Comment by dannephoto** [comment]
I'd love to test out a mac binary.

**Comment by PetteriAimonen** [comment]
@dannephoto @alsmithson There is now a Mac OS package available here for testing: https://jpa.kapsi.fi/jenkins/job/focus-stack/job/focus-stack%20MacOSX/lastSuccessfulBuild/artifact/distrib/focus-stack_MacOSX.zip

You'll need to allow it separately from system settings as it is unsigned.

**Comment by dannephoto** [comment]
Thanks a lot! 
Testing to download but seems interrupted(fails) everytime. Maybe Jenkins server. I´ll try harder and get back if I still can´t download it.

**Comment by PetteriAimonen** [comment]
Hmm, funny, it is proxied to behind my home connection but for me it still downloads in less than a minute.

I uploaded a copy here, perhaps it works better as this directory is on a faster connection: https://jpa.kapsi.fi/stuff/other/focus-stack_MacOSX.zip

**Comment by dannephoto** [comment]
Still slooow :).
what about sprend.com ?
Anyway. Gotta run. Will check in here later tonight again.

**Comment by PetteriAimonen** [comment]
@dannephoto I had a few friends try, works well for them. But for what it's worth, here's it on github: https://github.com/PetteriAimonen/focus-stack/releases/download/0.9/focus-stack_MacOSX.zip

I won't be distributing binaries over random file sharing services.

**Comment by dannephoto** [comment]
Thanks. Github did the trick.

**Comment by PetteriAimonen** [comment]
You can output any format supported by opencv with e.g. `--output=img.tiff`.

Averaging etc. other features might be added in future, but for now, the application is about focus stacking only. Focus stacking in itself tends to select the noisiest images of the stack, as they have the most contrast.
